const express = require("express");
const path = require("path");
const { verifyLocalToken } = require("../utils/localSign");
const { UPLOADS_ROOT } = require("../utils/uploads");

const router = express.Router();

// Serves a private local-disk upload after checking a short-lived signed
// token (see utils/localSign.js + utils/uploads.js#resolveFileUrl). This is
// the local-development counterpart to a Supabase signed URL — it exists so
// that a report saved under uploads/private/... is never reachable through
// the blanket /uploads static mount (see index.js), only through a link
// that expires.
router.get("/signed", (req, res) => {
  const relativePath = verifyLocalToken(req.query.token);
  if (!relativePath) {
    return res.status(410).json({ error: "This link has expired or is invalid." });
  }

  const filePath = path.join(UPLOADS_ROOT, relativePath.replace(/^\/uploads\//, ""));

  // Defense in depth: never serve a path outside UPLOADS_ROOT, even though
  // the token was generated by this same server and can't be forged without
  // JWT_SECRET.
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(path.resolve(UPLOADS_ROOT) + path.sep)) {
    return res.status(400).json({ error: "Invalid file reference." });
  }

  res.sendFile(resolved, (err) => {
    if (err && !res.headersSent) {
      res.status(404).json({ error: "File not found." });
    }
  });
});

module.exports = router;
